# Generated by Django 6.0 on 2026-01-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
    ]
