# Generated by Django 5.2.9 on 2026-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_device_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceissues',
            name='report_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
