# Generated by Django 5.2.11 on 2026-02-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_deviceissues_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
    ]
