# Generated by Django 5.2.11 on 2026-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_deviceissues_repaired_by_alter_deviceissues_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='block_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='floor_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
