# Generated by Django 5.2.11 on 2026-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_device_block_number_device_floor_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_specification',
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Reported', 'Reported')], default='Working', max_length=20),
        ),
    ]
