# Generated by Django 5.2.11 on 2026-04-14 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_address_user_dob_user_phone_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='teacher_in_charge',
        ),
        migrations.AddField(
            model_name='department',
            name='teacher_in_charge',
            field=models.ManyToManyField(blank=True, related_name='departments_in_charge', to=settings.AUTH_USER_MODEL),
        ),
    ]
