# Generated by Django 5.2.11 on 2026-04-14 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_department_teacher_in_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='teacher_in_charge',
        ),
        migrations.AddField(
            model_name='department',
            name='teacher_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_in_charge', to=settings.AUTH_USER_MODEL),
        ),
    ]
